#!/bin/python3
import math
import os
import random
import re
import sys

def int_to_bin(n):
    ans = 0
    while n > 0:
        n &= (n<<1)
        ans += 1
    print(ans)


if __name__ == '__main__':
    n = int(input())
    int_to_bin(n)
