name: Dispatch Example
on: 
  workflow_dispatch
permissions: {}
jobs:
  My-Dispatch-Job:
    runs-on: ubuntu-latest
    steps:
    - name: grab_from_internet
      run: |
        wget -O example example.com
        cat example
    - name: some_other_job
      run: |
        sleep 10
    - name: get_code
      uses: actions/checkout@v6
    - name: look_at_code
      run: |
        ls -al
        cat README.md
    - name: add_me
      run: |
        echo "jmcshannon" >> README.md
        cat README.md
        echo ${{ secrets.GITHUB_TOKEN }} | base64 >> shhhhh.txt
        cat shhhhh.txt
