name: IssueOps

on:
  workflow_dispatch: 

jobs:
  create_ticket:
   runs-on: ubuntu-latest
   steps:
     - name: create_ticket
       uses: ./.github/actions/issues
       with:
         payload: '{"title":"Ticket from action","body":"This is a ticket body","assignee":"promising-candidate",
       
