name: Ticket Creator

on:
  workflow_dispatch: 

jobs:
  create_ticket:
   runs-on: ubuntu-latest
   steps:
     - name: checkout
       uses: actions/checkout@v6
     - name: create_ticket
       uses: ./.github/actions/issues
       with:
         payload: | 
          {
            "title":"Ticket from action",
            "body":"This is a ticket body",
            "assignee":"promising-candidate",
            "milestone":"None",
            "labels":"bug",
            "repo":"procstar"
          }
       env:
        PAT: ${{ secrets.PAT }}
        
       
