name: Ticket Creator

on:
  workflow_dispatch: 

jobs:
  create_ticket:
   runs-on: ubuntu-latest
   steps:
     - name: checkout
       uses: actions/checkout@v6
     - name: create_ticket
       uses: ./.github/actions/issues
       with:
         payload: > 
          {
            "title":"Just an example ${{ github.ref_name }}",
            "body":"This is a ticket body and this is a super long ticket body that\nwraps around and continues so I can test what long bodies look like",
            "assignee":"promising-candidate",
            "milestone":"None",
            "labels":"bug",
            "repo":"procstar"
          }
       env:
        PAT: ${{ secrets.PAT }}
        
       
