name: IssueOps

on:
  issue_comment:
    types: created

jobs:
  IssueOps:
    if: contains(github.event.issue.title, 'Lab available for testing') && github.event.comment.body == 'Approved' && github.actor == 'promising-candidate'
    runs-on: ubuntu-latest
    steps:
    - name: create_var
      env:
        ISSUE_TITLE: ${{ github.event.issue.title }}
        ISSUE_COMMENT: ${{ github.event.comment.body }}
      run: |
        lab_name=$(printf '%s\n' "$ISSUE_TITLE" | grep -oP '(?<=Lab available for testing ).*')
        course=$(printf '%s\n' "$ISSUE_BODY" | grep -oP '$(?<=Course ).*') || true
        echo "course=$course" >> $GITHUB_ENV
        echo "lab_name=$lab_name" >> $GITHUB_ENV
    - name: Echo Vals
      run: |
        echo "$lab_name"
        if [[ -z "$course" ]]; then
          :
        fi
        
        
