name: IssueOps

on:
  issue_comment:
    types: created

jobs:
  IssueOps:
    if: github.event.comment.body == 'Approved' && github.actor == 'promising-candidate'
    runs-on: ubuntu-latest
    steps:
    - name: Echo Step
      run: |
        echo ${{ github.event.comment.body }}
        echo ${{ github.actor }}
        lab_name=$(echo "${{ github.event.issue.title }}" | grep -oP '(?<=Lab available for testing ).*')
        echo $lab_name
        
